# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  name: "<CHARTNAME>"

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

